//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsRental.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class RentalUsers
    {
        public int userID { get; set; }
        [Required(ErrorMessage ="Podaj prawid³ow¹ nazwê u¿ytkownika",AllowEmptyStrings =false)]
        public string login { get; set; }
        [Required(ErrorMessage ="Podaj prawid³owe has³o",AllowEmptyStrings =false)]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
